### PR TITLE
add optional additional scopes

### PR DESCRIPTION
**Pull request by joshbode**
Allow additional scopes to be requested.

Useful to allow reusing credentials for things like:
```
...
from flask import session
from googleapiclient.discovery import build
from oauth2client.client import AccessTokenCredentials
...
@app.callback(...)
def update(...):

    credentials = AccessTokenCredentials(session['google_oauth_token']['access_token'], 'sheets')
    service = build('sheets', 'v4', credentials=credentials)
    ...
```

### CODE REVIEW

**Comment by lchapo** [comment]
👍thanks for the contribution! I suggest modifying the additional scopes parameter to `additional_scopes=[]` and deleting the following two lines to keep it concise, then it's good to merge.

**Comment by joshbode** [comment]
Using mutable defaults for keyword arguments is discouraged in Python since you can end up mutating them :)

https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

I've moved the check to an inline check to make it more concise, though :)

**Comment by lchapo** [comment]
It shouldn't be an issue since you're only calling this method once in the class instantiation, but even so your approach does appear to be more pythonic. Looks good!

**Comment by joshbode** [comment]
Thanks!

**Pull request merged**
